name: Scala/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:

  sbt-cache:
    runs-on: ubuntu-latest
    
    steps:
      - name: check out source to find deps
        uses: actions/checkout@v2

      - name: launch SBT to pull in deps
        run: sbt

      - name: cache SBT
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}

  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: build
        run: sbt compile

      - name: unit tests
        run: sbt test
